pjt/tempProject/students/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    path('reg/', views.regStudent, name='reg'),
    path('regCon/', views.regConStudent, name='regCon'),
    path('all/', views.reaStudentAll, name='stuAll'),
    path('<str:name>/det/', views.detStudent, name='stuDet'),
    path('<str:name>/mod/', views.reaStudentOne, name='stuMod'),
	path('modCon/', views.modConStudent, name='modCon'),
	path('<str:name>/del', views.delConStudent, name='stuDel'),
]

pjt/tempProject/tempPjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
]

pjt/tempProject/students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    s_name = models.CharField(max_length=100)
    s_major = models.CharField(max_length=100)
    s_age = models.IntegerField(default=0)
    s_grade = models.IntegerField(default=0)
    s_gender = models.CharField(max_length=30)

    def __str__(self):
        return self.s_name

pjt/tempProject/students/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from students.models import Student

# Create your views here.
def regStudent(request):
    return render(request, 'students/registerStudent.html')

def regConStudent(request):
    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']

    qs = Student(s_name=name, s_major=major, s_age=age, s_grade=grade, s_gender=gender)
    qs.save()

    return HttpResponseRedirect(reverse('students:stuAll'))

def reaStudentAll(request):
    qs = Student.objects.all()
    context = {'student_list':qs}
    return render(request, 'students/readStudents.html', context)

def detStudent(request, name):
    qs = Student.objects.get(s_name = name)
    context = {'student_info':qs}
    return render(request, 'students/detailStudent.html', context)

def reaStudentOne(request, name):
	qs = Student.objects.get(s_name = name)
	context = {'student_info': qs}
	return render(request, 'students/modifyStudent.html', context)

def modConStudent(request):
	name = request.POST['name']
	major = request.POST['major']
	age = request.POST['age']
	grade = request.POST['grade']
	gender = request.POST['gender']

	s_qs = Student.objects.get(s_name = name)

	s_qs.s_name = name
	s_qs.s_major = major
	s_qs.s_age = age
	s_qs.s_grade = grade
	s_qs.s_gender = gender

	s_qs.save()

	return HttpResponseRedirect(reverse('students:stuAll'))

def delConStudent(request, name):
	qs = Student.objects.get(s_name = name)
	qs.delete()

	return HttpResponseRedirect(reverse('students:stuAll'))

pjt/tempProject/students/templates/students/detailStudent.html
<!DOCTYPE html>


<html>
	<head>
		<meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
		<title>Title</title>
	</head>

	<body>
		<p>Detail Students</p>

		{% if student_info %}
			name: {{student_info.s_name}}</br>
			major: {{student_info.s_major}}</br>
			age: {{student_info.s_age}}</br>
			grade: {{student_info.s_grade}}</br>
			gender: {{student_info.s_gender}}</br>
		{% else %}
			<p>student: 0</p>
		{% endif %}

		</br>

		<a href="{% url 'students:stuMod' student_info.s_name %}">수정</a>
		<a href="{% url 'students:stuDel' student_info.s_name %}">삭제</a>
		<a href="{% url 'students:stuAll' %}">학생리스트</a>
		<a href="{% url 'students:reg' %}">신규학생등록</a>

	</body>
</html>

pjt/tempProject/students/templates/students/modifyStudent.html
<!DOCTYPE html>


<html>
	<head>
		<meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
		<title>Title</title>
	</head>
	
	<body>
		<p>Modify Student</p>
		
		{% if student_info %}
			<form action="{% url 'students:modCon' %}" method="post">
				{% csrf_token %}
				name : {{student_info.s_name}}</br>
				<input type="hidden" name="name" value={{student_info.s_name}}></br>
				major : <input type="text" name="major" value={{student_info.s_major}}></br>
				age : <input type="text" name="age" value={{student_info.s_age}}></br>
				grade : <input type="text" name="grade" value={{student_info.s_grade}}></br>
				gender : <input type="text" name="gender" value={{student_info.s_gender}}></br>
				<input type="submit" name="Modify"></br>
		</form>
		{% else %}
			<p>student: 0</p>
		{% endif %}
		
		
		
	</body>
</html>

pjt/tempProject/students/templates/students/readStudents.html
<!DOCTYPE html>


<html>
	<head>
		<meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
		<title>Title</title>
	</head>

	<body>
		<p>Read Students</p>

		{% if student_list %}
		<ol>
			{% for s in student_list %}
			<li>
				<a href="{% url 'students:stuDet' s.s_name %}">{{s.s_name}}</a>
				<a href="{% url 'students:stuMod' s.s_name %}">수정</a>
				<a href="{% url 'students:stuDel' s.s_name %}">삭제</a>
			</li>
			{% endfor %}
		</ol>
		{% else %}
			<p>Student: 0</p>
		{% endif %}

		</br>

		<a href="{% url 'students:reg' %}">신규학생등록</a>

	</body>
</html>

pjt/tempProject/students/templates/students/registerStudent.html
<!DOCTYPE html>


<html>
	<head>
		<meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
		<title>Title</title>
	</head>

	<body>
		<p>Register Student</p>

		<form action="{% url 'students:regCon' %}" method="post">
		{% csrf_token %}
			name : <input type="text" name="name"></br>
			major : <input type="text" name="major"></br>
			age : <input type="text" name="age"></br>
			grade : <input type="text" name="grade"></br>
			gender : <input type="text" name="gender"></br>
			<input type="submit" name="Register"></br>
		</form>
	</body>
</html>